=== OpenSCAP/openscap/schemas/oval/5.11/oval-variables-schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:oval="http://oval.mitre.org/XMLSchema/oval-common-5" xmlns:oval-var="http://oval.mitre.org/XMLSchema/oval-variables-5" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:sch="http://purl.oclc.org/dsdl/schematron" targetNamespace="http://oval.mitre.org/XMLSchema/oval-variables-5" elementFormDefault="qualified" version="5.11">
     <xsd:import namespace="http://oval.mitre.org/XMLSchema/oval-common-5" schemaLocation="oval-common-schema.xsd"/>
     <xsd:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="../../common/xmldsig-core-schema.xsd"/>
     <xsd:annotation>
          <xsd:documentation/>
          <xsd:documentation>The following is a description of the elements, types, and attributes that compose the core schema for encoding Open Vulnerability and Assessment Language (OVAL) Variables. This schema is provided to give structure to any external variables and their values that an OVAL Definition is expecting.</xsd:documentation>
          <xsd:documentation>The OVAL Schema is maintained by The MITRE Corporation and developed by the public OVAL Community. For more information, including how to get involved in the project and how to submit change requests, please visit the OVAL website at http://oval.mitre.org.</xsd:documentation>
          <xsd:appinfo>
               <schema>Core Variable</schema>
               <version>5.11</version>
               <date>12/18/2014 09:00:00 AM</date>
               <terms_of_use>Copyright (c) 2002-2014, The MITRE Corporation. All rights reserved.  The contents of this file are subject to the terms of the OVAL License located at http://oval.mitre.org/oval/about/termsofuse.html. See the OVAL License for the specific language governing permissions and limitations for use of this schema.  When distributing copies of the OVAL Schema, this license header must be included.</terms_of_use>
              <sch:ns prefix="oval-var" uri="http://oval.mitre.org/XMLSchema/oval-variables-5"/>
          </xsd:appinfo>
     </xsd:annotation>
     <!-- =============================================================================== -->
     <!-- =============================================================================== -->
     <!-- =============================================================================== -->
     <xsd:element name="oval_variables">
          <xsd:annotation>
               <xsd:documentation>The oval_variables element is the root of an OVAL Variable Document. Its purpose is to bind together the different variables contained in the document. The generator section must be present and provides information about when the variable file was compiled and under what version. The optional Signature element allows an XML Signature as defined by the W3C to be attached to the document. This allows authentication and data integrity to be provided to the user. Enveloped signatures are supported. More information about the official W3C Recommendation regarding XML digital signatures can be found at http://www.w3.org/TR/xmldsig-core/.</xsd:documentation>
          </xsd:annotation>
          <xsd:complexType>
               <xsd:sequence>
                    <xsd:element name="generator" type="oval:GeneratorType" />
                    <xsd:element name="variables" type="oval-var:VariablesType" minOccurs="0" maxOccurs="1"/>
                    <xsd:element ref="ds:Signature" minOccurs="0" maxOccurs="1"/>
               </xsd:sequence>
          </xsd:complexType>
          <xsd:key name="varKey">
               <xsd:annotation>
                    <xsd:documentation>Enforce uniqueness amongst the variable ids found in the variable document.</xsd:documentation>
               </xsd:annotation>
               <xsd:selector xpath=".//oval-var:variable"/>
               <xsd:field xpath="@id"/>
          </xsd:key>
     </xsd:element>
     <!-- =============================================================================== -->
     <!-- =================================  GENERATOR  ================================= -->
     <!-- =============================================================================== -->
     <!--
		The GeneratorType is defined by the oval common schema.  Please refer to
		that documentation for a description of the complex type.
	-->
     <!-- =============================================================================== -->
     <!-- ================================  DEFINITIONS  ================================ -->
     <!-- =============================================================================== -->
     <xsd:complexType name="VariablesType">
          <xsd:annotation>
               <xsd:documentation>The VariablesType complex type is a container for one or more variable elements. Each variable element holds the value of an external variable used in an OVAL Definition. Please refer to the description of the VariableType for more information about an individual variable.</xsd:documentation>
          </xsd:annotation>
          <xsd:sequence>
               <xsd:element name="variable" type="oval-var:VariableType" minOccurs="1" maxOccurs="unbounded"/>
          </xsd:sequence>
     </xsd:complexType>
     <xsd:complexType name="VariableType">
          <xsd:annotation>
               <xsd:documentation>Each variable element contains the associated datatype and value which will be substituted into the OVAL Definition that is referencing this specific variable.</xsd:documentation>
               <xsd:documentation>The notes section of a variable should be used to hold information that might be helpful to someone examining the technical aspects of the variable. Please refer to the description of the NotesType complex type for more information about the notes element.</xsd:documentation>
          </xsd:annotation>
          <xsd:sequence>
               <xsd:element name="value" type="xsd:anySimpleType" minOccurs="1" maxOccurs="unbounded"/>
               <!-- JovalCM changed to ref oval:notes -->
               <xsd:element ref="oval:notes" minOccurs="0" maxOccurs="1"/>
          </xsd:sequence>
          <xsd:attribute name="id" type="oval:VariableIDPattern" use="required"/>
          <xsd:attribute name="datatype" use="required" type="oval:SimpleDatatypeEnumeration">
               <xsd:annotation>
                    <xsd:documentation>Note that the 'record' datatype is not permitted on variables.</xsd:documentation>
               </xsd:annotation>
          </xsd:attribute>
          <xsd:attribute name="comment" type="xsd:string" use="required"/>
     </xsd:complexType>
     <!-- =============================================================================== -->
     <!-- =================================  SIGNATURE  ================================= -->
     <!-- =============================================================================== -->
     <!--
		The signature element is defined by the xmldsig schema.  Please refer to that
		documentation for a description of the valid elements and types.  More
		information about the official W3C Recommendation regarding XML digital
		signatures can be found at http://www.w3.org/TR/xmldsig-core/.
	-->
     <!-- =============================================================================== -->
     <!-- =============================================================================== -->
     <!-- =============================================================================== -->
</xsd:schema>

=== OpenSCAP/openscap/tests/API/OVAL/unittests/linux-external-variables.xml
<?xml version="1.0" encoding="UTF-8"?> 
<oval_variables xmlns="http://oval.mitre.org/XMLSchema/oval-variables-5" 
    xmlns:oval="http://oval.mitre.org/XMLSchema/oval-common-5" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://oval.mitre.org/XMLSchema/oval-variables-5 oval-variables-schema.xsd http://oval.mitre.org/XMLSchema/oval-common-5 oval-common-schema.xsd"> 
    <generator> 
      <oval:schema_version>5.10.1</oval:schema_version> 
      <oval:timestamp>2006-09-18T15:24:29.903-04:00</oval:timestamp> 
      <terms_of_use>Copyright (c) 2002-2012, The MITRE Corporation. All rights reserved. The contents of this file are subject to the license described in terms.txt.</terms_of_use>
    </generator> 
    <variables> 
        <variable id="oval:org.mitre.oval.test:var:566" datatype="binary" comment="This variable represents the binary value '0000'"> 
            <value>0000</value>
        </variable> 
        <variable id="oval:org.mitre.oval.test:var:505" datatype="binary" comment="This variable represents the binary values '0000', '0010', '0100', and '1000'."> 
            <value>0000</value>
            <value>0010</value>
            <value>0100</value>
            <value>1000</value>
        </variable>
        <variable id="oval:org.mitre.oval.test:var:453" datatype="boolean" comment="This variable represents the boolean value 'true'"> 
            <value>true</value>
        </variable> 
        <variable id="oval:org.mitre.oval.test:var:983" datatype="boolean" comment="This variable represents the boolean values 'true', 'false', '0', and '1'."> 
            <value>true</value>
            <value>false</value>
            <value>0</value>
            <value>1</value>
        </variable>
        <variable id="oval:org.mitre.oval.test:var:89" datatype="evr_string" comment="This variable represents the evr_string value '1:2.3.4-5.6'."> 
            <value>1:2.3.4-5.6</value>
        </variable> 
        <variable id="oval:org.mitre.oval.test:var:51" datatype="evr_string" comment="This variable represents the evr_string values '1:2.3.4-5.6', '1:2.3.4-5.7', '1:2.3.4-5.8', and '1:2.3.4-5.9'."> 
            <value>1:2.3.4-5.6</value>
            <value>1:2.3.4-5.7</value>
            <value>1:2.3.4-5.8</value>
            <value>1:2.3.4-5.9</value>
        </variable>
        <variable id="oval:org.mitre.oval.test:var:592" datatype="float" comment="This variable represents the float value '1.23456'."> 
            <value>1.23456</value>
        </variable> 
        <variable id="oval:org.mitre.oval.test:var:964" datatype="float" comment="This variable represents the float values '1.23456', '-3.542E2', '100e-4', '-.4323e-3'."> 
            <value>1.23456</value>
            <value>-3.542E2</value>
            <value>100e-4</value>
            <value>-.4323e-3</value>
        </variable>
        <variable id="oval:org.mitre.oval.test:var:621" datatype="int" comment="This variable represents the integer value '0'."> 
            <value>0</value>
        </variable> 
        <variable id="oval:org.mitre.oval.test:var:199" datatype="int" comment="This variable represents the integer values '0', '-35422', '1004', and '-43233'."> 
            <value>0</value>
            <value>-35422</value>
            <value>1004</value>
            <value>-43233</value>
        </variable>
        <variable id="oval:org.mitre.oval.test:var:183" datatype="string" comment="This variable represents the string value 'test_string_1'."> 
            <value>test_string_1</value>
        </variable> 
        <variable id="oval:org.mitre.oval.test:var:86" datatype="string" comment="This variable represents the string values 'test_string_1', 'test_string_2', 'test_string_3', and 'test_string_4'."> 
            <value>test_string_1</value>
            <value>test_string_2</value>
            <value>test_string_3</value>
            <value>test_string_4</value>
        </variable>
        <variable id="oval:org.mitre.oval.test:var:110" datatype="version" comment="This variable represents the version value '1.2.3.4'."> 
            <value>1.2.3.4</value>
        </variable> 
        <variable id="oval:org.mitre.oval.test:var:215" datatype="version" comment="This variable represents the version values '1.2.3.4', '1a2s3d4', '1.2.3-04', and '1.2+3.4'."> 
            <value>1.2.3.4</value>
            <value>1a2s3d4</value>
            <value>1.2.3-04</value>
            <value>1.2+3.4</value>
        </variable>
        <variable id="oval:org.mitre.oval.test:var:629" datatype="string" comment="This variable represents the string value '123-456-7890'."> 
            <value>123-456-7890</value>
        </variable> 
        <variable id="oval:org.mitre.oval.test:var:327" datatype="string" comment="This variable represents the string value '1-123-456-7890'."> 
            <value>1-123-456-7890</value>
        </variable> 
        <variable id="oval:org.mitre.oval.test:var:642" datatype="int" comment="This variable represents the integer value '0'."> 
            <value>0</value>
        </variable> 
        <variable id="oval:org.mitre.oval.test:var:863" datatype="int" comment="This variable represents the integer value '1'."> 
            <value>1</value>
        </variable> 
    </variables> 
</oval_variables>

=== OpenSCAP/openscap/tests/API/OVAL/unittests/external_variables.xml
<?xml version="1.0" encoding="UTF-8"?>
<oval_variables xmlns="http://oval.mitre.org/XMLSchema/oval-variables-5"
    xmlns:oval="http://oval.mitre.org/XMLSchema/oval-common-5"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://oval.mitre.org/XMLSchema/oval-variables-5 oval-variables-schema.xsd http://oval.mitre.org/XMLSchema/oval-common-5 oval-common-schema.xsd">
    <generator>
      <oval:schema_version>5.11</oval:schema_version>
      <oval:timestamp>2015-06-12T15:24:29.903-04:00</oval:timestamp>
    </generator>
    <variables>
        <variable id="oval:x:var:1" datatype="int" comment="This variable represents the integer value '1'.">
            <value>1</value>
        </variable>
        <variable id="oval:x:var:2" datatype="int" comment="This variable represents the integer value '1'.">
            <value>1</value>
        </variable>
        <variable id="oval:x:var:3" datatype="int" comment="This variable represents the integer value '1'.">
            <value>1</value>
        </variable>
        <variable id="oval:x:var:4" datatype="int" comment="This variable represents the integer value '1'.">
            <value>1</value>
        </variable>
    </variables>
</oval_variables>
